name: push-aws-or-azure
on: 
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      cloud:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: false
      aws-secret-access-key:
        required: false
      azure_credentials:
        required: false

jobs:
  aws:
    name: AWS
    if: inputs.cloud == 'aws'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: l2a4m1h7
          REPOSITORY: ${{ inputs.repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd src
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG

  azure:
    name: AZURE
    if: inputs.cloud == 'azure'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure AZURE Credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: aws
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image app=public.ecr.aws/l2a4m1h7/repo-aws:${{ github.sha }}
          cat kustomization.yaml

      - name: commit
        run: |
          git config --local user.email "gha@github.com"
          git config --local user.name "gha"
          git commit -am "Changing image tag to ${{ github.sha }}"

      - name: push
        uses: ad-m/github-push-action@master
